Add reminder of advantage of being in systemd-journal
https://lists.freedesktop.org/archives/systemd-devel/2016-October/037554.html

diff --git a/bin/jcu b/bin/jcu
--- a/bin/jcu
+++ b/bin/jcu
@@ -1,3 +1,12 @@
 #!/bin/bash
 
+# Poettering's info on --user and systemd-journal gid:
+#
+#   https://lists.freedesktop.org/archives/systemd-devel/2016-October/037554.html
+#
+# if ! groups | grep -q systemd-journal; then
+#     echo >&2 "Need to be in systemd-journal group; aborting!"
+#     exit 1
+# fi
+
 journalctl --user "$@"
