to stderr

diff --git a/bin/mnt-initrd b/bin/mnt-initrd
--- a/bin/mnt-initrd
+++ b/bin/mnt-initrd
@@ -8,7 +8,7 @@ if [[ "$OSTYPE" != linux* ]]; then
 fi
 
 if [[ `id -u` != 0 ]]; then
-  echo "Not root; aborting."
+  echo "Not root; aborting." >&2
   exit 1
 fi
 
