*** empty log message ***

diff --git a/bin/pdf b/bin/pdf
--- a/bin/pdf
+++ b/bin/pdf
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+viewers='kpdf evince acroread xpdf'
+
 found=
 for file in "$@"; do
     if [ -r "$file" ]; then
@@ -10,8 +12,8 @@ for file in "$@"; do
 done
 
 if [ -z "$found" ]; then
-  echo "No valid file found; aborting!" >&2
-  exit 1
+    echo "No valid file found; aborting!" >&2
+    exit 1
 fi
 
 # acroread -help gets truncated before echoing 'openInNewWindow'
@@ -20,10 +22,27 @@ fi
 # if acroread -helpall | grep -q openInNewWindow; then
   acro_opts=-openInNewWindow
 # else
-#   acro_opts=
+#     acro_opts=
 # fi
 
-kpdf "$@" || \
-evince "$@" || \
-acroread $acro_opts "$@" || \
-xpdf "$@"
+exe=
+for exe_check in $viewers; do
+    if which $exe_check >/dev/null 2>&1; then
+        exe=$exe_check
+#        echo "Will use $exe ..."
+        break
+    else
+#        echo "$exe_check not found"
+    fi
+done
+
+if [ -z "$exe" ]; then
+    echo "No PDF viewer found; aborting." >&2
+    exit 1
+fi
+
+if [ "$exe" = "acroread" ]; then
+    opts="$acro_opts"
+fi
+
+"$exe" $opts "$@"
