allow searching for process subtrees by process command substring

diff --git a/bin/pst b/bin/pst
--- a/bin/pst
+++ b/bin/pst
@@ -1,15 +1,43 @@
-#!/bin/sh
+#!/bin/bash
+
+linux_detect_ascii () {
+    ascii=
+    pstree --help 2>&1 | grep -q -- '-A .*ASCII' && ascii=-A
+}
+
+linux_pstree () {
+    LANG=C pstree $ascii -p "$@"
+}
+
+linux_iterate () {
+    if [ $# = 0 ]; then
+        linux_pstree
+    elif [ -d "/proc/$1" ]; then
+        linux_pstree "$@"
+    else
+        for proc in "$@"; do
+            echo "Searching for processes containing '$proc' ..."
+            for pid in `pgrep -f "$proc"`; do
+                #echo "Tree for pid $pid:"
+                linux_pstree "$pid"
+            done
+        done
+    fi
+}
 
 case "$OSTYPE" in
-  solaris*) exec ptree     "$@" | less -rS ;;
-         *) if which pstree 2>&1 >/dev/null; then
-              ascii=
-              pstree --help 2>&1 | grep -q -- '-A .*ASCII' && ascii=-A
-              LANG=C pstree $ascii -p "$@" | less -rS
-            else
-              echo "pstree not found."
-              exit 1
-            fi
-            ;;
+    solaris*)
+        exec ptree "$@" | less -rS
+        ;;
+    *)
+        if ! which pstree 2>&1 >/dev/null; then
+            echo "pstree not found."
+            exit 1
+        fi
+
+        linux_detect_ascii
+
+        linux_iterate "$@" | less -rS
+        ;;
 esac
 
