ssta -> sta and add user service commands

diff --git a/bin/service-commands b/bin/service-commands
--- a/bin/service-commands
+++ b/bin/service-commands
@@ -9,7 +9,7 @@ if [ "$mode" = "$me" ] && [ -z "$*" ]; then
   here=`dirname $0`
   echo -n "Setting up handy service shortcuts in $here ... "
   cd "$here"
-  for op in s{re,rl,st,sp,sta}; do
+  for op in {,u}s{re,rl,st,sp,ta}; do
     if ! [ -e $op ]; then
         ln -s $me $op
         echo -n " $op"
@@ -19,19 +19,32 @@ if [ "$mode" = "$me" ] && [ -z "$*" ]; then
   exit 0
 fi
 
+user=
+case "$mode" in
+  u*)
+    user=--user
+    mode="${mode#u}"
+    ;;
+esac
+
 case "$mode" in
   sre)  op=restart ;;
   srl)  op=reload  ;;
   sst)  op=start   ;;
   ssp)  op=stop    ;;
-  ssta) op=status  ;;
+  sta)  op=status  ;;
   *)   echo "$0: BUG with mode '$mode'"; exit 1 ;;
 esac
 
 service="$1"
-shift
+if [ -n "$1" ]; then
+    shift
+elif [ "$op" != status ]; then
+    echo >&2 "Missing service name; aborting"
+    exit 1
+fi
 
-if [ "`id -u`" != 0 ]; then
+if [ "`id -u`" != 0 ] && [ -z "$user" ]; then
   # 'ave a go son
   sudo=sudo
 else
@@ -39,11 +52,11 @@ else
 fi
 
 if which systemctl >&/dev/null; then
-  exec $sudo systemctl $op "$service" "$@"
+  exec $sudo systemctl $user $op $service "$@"
 elif [ -x /sbin/service ]; then
-  # Red Hat
+  # legacy v1
   exec $sudo /sbin/service "$service" $op "$@"
 else
-  # others, e.g. SUSE
+  # legacy v2
   exec $sudo /etc/init.d/"$service" $op "$@"
 fi
