Don't exit 0 on failure.

diff --git a/.cfg-post.d/cron b/.cfg-post.d/cron
--- a/.cfg-post.d/cron
+++ b/.cfg-post.d/cron
@@ -8,10 +8,14 @@ source "$ZDOTDIR/lib/libhooks.sh"
 crontab -l > "$config"
 
 # FIXME: doesn't work if no crontab exists
-if rebuild_config "$config" "$confdir"; then
-    if ( echo; cat "$config" ) | crontab -; then
-        echo "Reinstalled user's crontab"
-    else
-        echo "WARNING: Failed to reinstall user's crontab" >&2
-    fi
+if ! rebuild_config "$config" "$confdir"; then
+    echo "ERROR: failed to rebuild $config from $confdir" >&2
+    exit 1
+fi
+
+if ( echo; cat "$config" ) | crontab -; then
+    echo "Reinstalled user's crontab"
+else
+    echo "WARNING: Failed to reinstall user's crontab" >&2
+    exit 1
 fi
