fix nasty clash with rvm's use of $hook

diff --git a/.zsh/functions/run_hooks b/.zsh/functions/run_hooks
--- a/.zsh/functions/run_hooks
+++ b/.zsh/functions/run_hooks
@@ -12,25 +12,25 @@
 : ${DEBUG_LOCAL_HOOKS:=0}
 
 process_hook () {
-  hook_path="$1"
+  zdot_hook_path="$1"
 
-  if ! [ -r "$hook_path" ]; then
+  if ! [ -r "$zdot_hook_path" ]; then
     if [ "$DEBUG_LOCAL_HOOKS" -ge 2 ]; then
-      echo "Couldn't read $hook_path; skipping." >&2
+      echo "Couldn't read $zdot_hook_path; skipping." >&2
     fi
     return 0
   fi
   
   if [ -z "$hooks_found" ]; then
-    hooks_found="$hook_path"
+    hooks_found="$zdot_hook_path"
   else
-    hooks_found="$hooks_found $hook_path"
+    hooks_found="$hooks_found $zdot_hook_path"
   fi
 
-  case "$action" in
+  case "$zdot_action" in
     source)
-      [ "$DEBUG_LOCAL_HOOKS" -gt 0 ] && sh_load_status "$hook_path"
-      source "$hook_path"
+      [ "$DEBUG_LOCAL_HOOKS" -gt 0 ] && sh_load_status "$zdot_hook_path"
+      source "$zdot_hook_path"
       ;;
     find)
       ;;
@@ -67,9 +67,14 @@ iterate_hooks () {
     return 1
   fi
 
-  action="$1"
-  hook="$2"
+  zdot_action="$1"
+  zdot_hook="$2"
 #   origdir="`pwd`"
+
+  if [ -z "$zdot_hook" ]; then
+    echo "BUG: iterate_hooks called with empty hook name: $*" >&2
+    return 1
+  fi
 
   hooks_found=
 
@@ -90,36 +95,36 @@ iterate_hooks () {
       continue
     fi
 
-    hook_d="$dir/$hook"
+    zdot_hook_d="$dir/$zdot_hook"
 
     # Detect obsolete files from run_local_hooks
-    for hook_path in ${hook_d%%.d}.*; do
-      [ "$hook_path" = "$hook_d" ] && continue
-      if should_ignore "$hook_path"; then
+    for zdot_hook_path in ${zdot_hook_d%%.d}.*; do
+      [ "$zdot_hook_path" = "$zdot_hook_d" ] && continue
+      if should_ignore "$zdot_hook_path"; then
         if [ "$DEBUG_LOCAL_HOOKS" -ge 5 ]; then
-          echo "# Ignoring obsolete hook $hook_path"
+          echo "# Ignoring obsolete hook $zdot_hook_path"
         fi
         continue
       elif [ "$DEBUG_LOCAL_HOOKS" -ge 2 ]; then
-        echo "WARNING: found obsolete hook $hook_path" >&2
+        echo "WARNING: found obsolete hook $zdot_hook_path" >&2
       fi
     done
 
-    [ -d "$hook_d" ] || break
+    [ -d "$zdot_hook_d" ] || break
 
-#     if ! cd "$hook_d"; then
-#       echo "BUG?  Couldn't cd to $hook_d" >&2
+#     if ! cd "$zdot_hook_d"; then
+#       echo "BUG?  Couldn't cd to $zdot_hook_d" >&2
 #       return 1
 #     fi
 
     hostnick=$(cat $ZDOTDIR/.localhost-nickname)
     : ${hostnick:=unknown}
 
-    for hook_path in $hook_d/*; do
-      dirent="${hook_path##*/}"
+    for zdot_hook_path in $zdot_hook_d/*; do
+      dirent="${zdot_hook_path##*/}"
 
       if [ "$DEBUG_LOCAL_HOOKS" -ge 3 ]; then
-        echo "# Considering possible hook $hook_path"
+        echo "# Considering possible hook $zdot_hook_path"
       fi
 
       if should_ignore "$dirent"; then
@@ -145,7 +150,7 @@ iterate_hooks () {
              [ "${hostnick}"     != "${host%%.*}" ]
           then
             [ "$DEBUG_LOCAL_HOOKS" -ge 4 ] && \
-              echo "#   $hook_path hostname $host does not match \$HOSTNAME $HOSTNAME"
+              echo "#   $zdot_hook_path hostname $host does not match \$HOSTNAME $HOSTNAME"
             continue
           fi
           special=y
@@ -153,12 +158,12 @@ iterate_hooks () {
         uid-*)
           uid="${dirent#uid-}"
           if [ "$uid" = 'OWNER' ]; then
-            uid=$( stat -c '%U' "$hook_path" ) # portable?
-#            uid=$( command ls -l "$hook_path" | awk '{print $3}' ) # sucks
+            uid=$( stat -c '%U' "$zdot_hook_path" ) # portable?
+#            uid=$( command ls -l "$zdot_hook_path" | awk '{print $3}' ) # sucks
           fi
           if [ "$USERNAME" != "$uid" ]; then
             [ "$DEBUG_LOCAL_HOOKS" -ge 4 ] && \
-              echo "#   $hook_path uid $uid does not match \$USERNAME $USERNAME"
+              echo "#   $zdot_hook_path uid $uid does not match \$USERNAME $USERNAME"
             continue
           fi
           special=y
@@ -167,9 +172,9 @@ iterate_hooks () {
 
       if [ -n "$special" ]; then
         [ "$DEBUG_LOCAL_HOOKS" -ge 4 ] && \
-          echo "# $hook_path is a special case hook"
-        if [ -d "$hook_path" ]; then
-          for subhook in $hook_path/*; do
+          echo "# $zdot_hook_path is a special case hook"
+        if [ -d "$zdot_hook_path" ]; then
+          for subhook in $zdot_hook_path/*; do
             if should_ignore "$subhook"; then
               if [ "$DEBUG_LOCAL_HOOKS" -ge 5 ]; then
                 echo "# Ignoring possible subhook $subhook"
@@ -178,16 +183,16 @@ iterate_hooks () {
             fi
             process_hook "$subhook"
           done
-        elif [ -f "$hook_path" ]; then
-          echo "WARNING: $hook_path should be a directory not a file" >&2
-          process_hook "$hook_path"
+        elif [ -f "$zdot_hook_path" ]; then
+          echo "WARNING: $zdot_hook_path should be a directory not a file" >&2
+          process_hook "$zdot_hook_path"
         else
-          echo "WARNING: $hook_path was not a directory or even a file" >&2
-          file "$hook_path" >&2
+          echo "WARNING: $zdot_hook_path was not a directory or even a file" >&2
+          file "$zdot_hook_path" >&2
         fi
       else
-        if ! [ -d "$hook_path" ]; then
-          process_hook "$hook_path"
+        if ! [ -d "$zdot_hook_path" ]; then
+          process_hook "$zdot_hook_path"
         fi
       fi
     done
